# Generated by Django 2.0.9 on 2018-11-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='holder',
            field=models.CharField(choices=[('NA', '国立図書館'), ('PR', '県立図書館'), ('CI', '市立図書館')], max_length=10),
        ),
    ]
