# Generated by Django 2.0.9 on 2018-11-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20181125_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='holder',
            field=models.CharField(choices=[('国立図書館', '国立図書館'), ('県立図書館', '県立図書館'), ('市立図書館', '市立図書館')], max_length=10),
        ),
    ]
