# Generated by Django 2.0.9 on 2018-12-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20181125_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
